Server db
sjunel/inventory-mgmt pull request #1
Opened 2022-10-21 19:47 UTC by sjunel

This is general setup for the app. The purpose of the app is to allow users to add skincare products to their homepage/dashboard area and manage inventory in the sense of tracking details about these products.

2022-10-22 01:12 UTC, abechoe requested changes

2022-10-22 01:12 UTC, abechoe commented on README.md
> +```
Would be good to add directions on how to get the dependencies installed and the apps running, e.g. `npm install` and `npm run start`

2022-10-22 01:12 UTC, abechoe commented on schema.sql
> +  fill_size_oz int,
my suggestion here would be to store the full size in a base unit, instead of having one column per unit. You can handle the unit conversions after querying (if needed)

2022-10-22 01:12 UTC, abechoe commented on index.js
> +app.listen(PORT, ()=> {
It would be useful to handle the case where this PORT is already used (or is just unavailable for some reason)

2022-10-22 01:12 UTC, abechoe commented on README.md
> +psql -d inventory-mgmt < schema.sql
This would be nice to have in an `npm` script, e.g. `npm run setupDB`

2022-10-22 02:42 UTC, sjunel commented on schema.sql
> +  fill_size_oz int,
Okay, I hear what you're saying. My initial thought was that sometimes a product only lists fl oz or mL, so a user could have the option of inputting info for one unit or the other without handling the conversion themselves. I'll go with your suggestion here though and choose one; maybe it would be nice to add a way on the front end for the user to input either format, and then the server can handle the unit conversion before storing it in the db.

2022-10-24 20:27 UTC, abechoe approved these changes

2022-10-24 20:48 UTC, becha2 approved these changes

2022-10-24 20:50 UTC, merged